---
label: Recipe
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Title
  default: Recipe Title
- type: textarea
  label: Recipe
  name: recipe
  default: Recipe Body
pages:
- _posts/berry-smoothie.md
- _posts/2018-11-28-grape-cauliflower-curry-salad.md
