---
label: Recipe
hide_body: false
fields:
- type: text
  name: title
  label: Title
  default: Recipe Title
- type: textarea
  label: Recipe
  name: recipe
  default: Recipe Body
- type: tag_list
  name: tags
  label: Tags
  default: []
pages:
- _posts/2018-11-29-berry-smoothie.md
- _posts/2019-02-03-african-chickpea-stew.md
- _posts/grape-cauliflower-curry-salad.md
- _posts/vegetable-noodle-soup-ginger-miso-broth.md
